## docker-compose.yml

# https://github.com/jdischler/GrazeScapeServer

version: '3.8'

services:

  app:
    image: grazescape_svr:0.1
    environment:
      db_host: "postgres"
      db_port: "5432"
      db_name: "GrazeScape"
      db_user: "postgres"
      db_pass: "GrazeScape"
      play_http_secret_key: 'LBKDRO/a42tZ6BfaHkTyYGvNjjqHiOVYSYQq4upLOIc'
    volumes:
      - type: bind
        source: "./layerData" ## dir must be prepopulated on host
        target: "/opt/docker/layerData"
    networks:
      internal:
        aliases:
          - grazescape
      external:
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
    depends_on:
      - "db"

  db:
    image: postgis/postgis:13-master
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "GrazeScape"
      POSTGRES_DB: "GrazeScape"
    networks:
      internal:
        aliases:
          - postgres
    ports:
      - target: 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  external:
  internal:


